import Head from "next/head";
import { Ubuntu } from "@next/font/google";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import About from "@/components/About";
import WorkExperience from "@/components/WorkExperience";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import ContactMe from "@/components/ContactMe";
import Link from "next/link";
import Image from "next/image";

const ubuntu = Ubuntu({ subsets: ["cyrillic"], weight: "400" });

export default function Home() {
  return (
    <div className="bg-[#2E3040] text-white overflow-y-scroll z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#5ED3F3]/80">
      <div className={ubuntu.className}>
        <Head>
          <title>bodik_87 Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <section id="hero">
          <Hero />
        </section>
        {/* <section id="about">
          <About />
        </section> */}
        {/* <section id="experience">
          <WorkExperience />
        </section> */}

        <section id="projects">
          <Projects />
        </section>
        <section id="skills">
          <Skills />
        </section>
        <section id="contact">
          <ContactMe />
        </section>
        <Link href="#hero">
          <footer className="sticky bottom-5 left-5 w-fit cursor-pointer">
            <div className="flex items-center justify-center">
              <Image
                src="/photo.jpg"
                alt="Hero"
                className="rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
                width={40}
                height={40}
                priority
              />
            </div>
          </footer>
        </Link>
      </div>
    </div>
  );
}
